version: '2'

services:
  rethinkdb:
    env_file: .env
    restart: always
    image: rethinkdb:2.3
    ports:
      - "8083:8080"
      - "8084:28015"
      - "8085:29015"

  proxy:
    env_file: .env
    restart: always
    image: ehazlett/docker-proxy:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "2376:2375"
    command: -D

  swarm:
    env_file: .env
    restart: always
    image: swarm:1.2.0
    command: m --host tcp://0.0.0.0:2375 proxy:2375
    ports:
      - "2375"

  controller:
    env_file: .env
    restart: always
    image: ilmhpe/ilm
    entrypoint: /bin/bash
    command: -c "sleep 30 && ./shipyard -D server --rethinkdb-addr rethinkdb:28015 -d tcp://swarm:2375"
    volumes_from:
      - proxy
    ports:
      - "8082:8080"
      - "9279"
    depends_on:
      - rethinkdb

  postgres:
    hostname: postgres
    image: postgres:9.4.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  clair:
    env_file: .env
    image: quay.io/eedevops/clair:ilm-v1.0.1
    volumes:
      - ./clair_config:/config:ro
      - /tmp/clair-data:/tmp
    entrypoint: /bin/bash
    command: -c "sleep 30 && clair --config=/config/config.yaml"
    ports:
      - "6060:6060"
      - "6061:6061"
    depends_on:
      - postgres
      - controller

  notary_server:
    volumes:
      - /tmp/server-configdir/fixtures:/etc/docker/notary-server/
    environment:
      - NOTARY_SERVER_TRUST_SERVICE_TYPE=local
      - NOTARY_SERVER_STORAGE_BACKEND=memory
      - NOTARY_SERVER_LOGGING_LEVEL=debug
    image: notary:server-0.3.0
    networks:
      - mdb
      - sig
    ports:
      - "8080"
      - "4443:4443"
    entrypoint: /usr/bin/env sh
    command: -c "notary-server -config=/etc/docker/notary-server/server-config.json"
    depends_on:
      - notary_mysql
      - notary_signer
      - controller

  notary_signer:
    volumes:
      - /tmp/server-configdir/fixtures:/etc/docker/notary-server/
    image: notary:signer-0.3.0
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    command: -c "notary-signer -config=/etc/docker/notary-server/signer-config.json"
    depends_on:
      - notary_mysql
      - controller

  notary_mysql:
    networks:
      - mdb
    volumes:
      - ./notarymysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - notary_data:/var/lib/mysql
    image: mariadb:10.1.10
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table

volumes:
  notary_data:
    external: false
networks:
  mdb:
    external: false
  sig:
    external: false
